services:
  zoomrec:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEBUG=True
    volumes:
      - ./recordings:/home/zoomrec/recordings
      - ./example/audio:/home/zoomrec/audio
      - ./example/meetings.csv:/home/zoomrec/meetings.csv:ro
    ports:
      - "5901:5901"
    security_opt:
      - seccomp:unconfined 